# Generated by Django 2.2.12 on 2021-05-28 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
