# Generated by Django 2.2.12 on 2021-05-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_remove_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('commenter', models.CharField(max_length=20)),
                ('post', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20)),
                ('image', models.URLField(max_length=100000, null=True)),
                ('caption', models.CharField(max_length=100, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.IntegerField()),
                ('post', models.IntegerField()),
            ],
        ),
    ]
